/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 96a180effda30f3cf79c812e772afbe8)
interface __BaseEnv_Env {
	STAR_HISTORY: KVNamespace;
	CHALLENGE_DB: D1Database;
	CHALLENGE_API_RATE_LIMITER: RateLimit;
	CHALLENGE_CREATE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
